services:
  seq:
    image: datalust/seq:latest
    container_name: mazadzone-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "5341:5341" 
      - "8081:80"  
    volumes:
      - seq-data:/data
    networks:
      backend_network:
        aliases:
          - seq

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mazadzone-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd!
      - MSSQL_PID=Developer
    ports:
      - "2222:1433" 
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      backend_network:
        aliases:
          - sqlserver
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: mazadzone-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      backend_network:
        aliases:
          - redis

  api:
    build:
      context: . 
      dockerfile: src/MazadZone.Api/Dockerfile
    container_name: mazadzone-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MazadZoneDb=Server=sqlserver,1433;Database=MazadZoneDb;User Id=sa;Password=YourStrong@Passw0rd!;TrustServerCertificate=True;
      - ConnectionStrings__Redis=redis:6379
    ports:
      - "5108:8080"
    depends_on:
      - sqlserver
      - redis
      - seq
    networks:
      - frontend_network
      - backend_network

volumes:
  seq-data:
  sql-data:
  redis-data:

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge